name: "Lesson 3 - Exercise 1"

on:
  workflow_call:
    inputs:
      actor:
        required: true
        type: string

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings message
        run: |
          echo "Well done: $ACTOR you've implemented reusable workflows successfully!"
        env:
          ACTOR: ${{ inputs.actor }}
